version: "3"

services:
    crm-inventory:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app:cached
        
        command: uvicorn crm_inventory.app:app --host 0.0.0.0 --port 8000 --reload